name: Stock Tracker CI

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change this to your desired Python version

      - name: Install dependencies
        run: pip install pandas gspread oauth2client beautifulsoup4 nltk

      - name: Run Python code
        run: |
          # Add a conditional check to skip running the code if emaillist.csv is modified
          if [[ $(git diff --name-only HEAD^ HEAD | grep -c 'emaillist.csv') -eq 0 ]]; then
            python Red-Alert-ThirdPart.py
          else
            echo "Skipping code execution because emaillist.csv was modified"
          fi
